### ISSUE TITLE
style: Landing page instagram icon button on hover background color does not follow theme style

### ISSUE THREAD

**Issue by OkkarMin** [lhinjy/twopointfyve#1]
![IMAGE 2021-06-16 19:06:49](https://user-images.githubusercontent.com/24297303/122208529-00ff8100-ced6-11eb-9a9a-f09200bc8d2e.jpg)

As seen above, the icon button background color does not follow the theme style of the site.

Take a look at https://chakra-ui.com/docs/features/style-props#pseudo to make use of `_hover` attribute to change the background color on hover

**Comment by lhinjy** [comment]
Thank you very much for noticing and bringing it up to me. 

Fixed in lhinjy@e7acde388ed0817b099853d0e549e946267ef9d6
